# -*- coding: utf-8 -*-
"""funcoes_auxiliares.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gKbaV-NQdeLHkDOt52rOYIvWF5iV-_zK
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from debug_utils import debug_show
import os

from scipy.stats import weightedtau
from utility_functions import UtilityFunctions

PASTA_FIGURAS = "figuras"

os.makedirs(PASTA_FIGURAS, exist_ok=True)


# =================================================
# Para plotar o gráfico gif
# =================================================

def plotar_evolucao_utilidades_estatica(
    interpoladores,
    historico_modelos,
    save_path=None
):

    num_criterios = len(interpoladores)

    fig, axes = plt.subplots(
        1,
        num_criterios,
        figsize=(6 * num_criterios, 5)
    )

    if num_criterios == 1:
        axes = [axes]

    # =====================================================
    # Cores progressivas
    # =====================================================

    cmap = plt.cm.viridis

    num_iteracoes = len(historico_modelos)

    cores = [
        cmap(i / max(1, num_iteracoes - 1))
        for i in range(num_iteracoes)
    ]

    # =====================================================
    # Critérios
    # =====================================================

    for j, ax in enumerate(axes):

        # -------------------------------------------------
        # Curva real
        # -------------------------------------------------

        x_min = interpoladores[j].x.min()

        x_max = interpoladores[j].x.max()

        x_real = np.linspace(
            x_min,
            x_max,
            300
        )

        y_real = interpoladores[j](x_real)

        ax.plot(
            x_real,
            y_real,
            color="black",
            linewidth=3,
            label="Real"
        )

        # -------------------------------------------------
        # Curvas UTASTAR
        # -------------------------------------------------

        for idx, modelo_uta in enumerate(historico_modelos):

            grupo = modelo_uta.grupos_w[j]

            w_j = modelo_uta.media_geral[grupo]

            y_rec = np.concatenate([
                [0],
                np.cumsum(w_j)
            ])

            x_rec = modelo_uta.niveis[j]

            ax.plot(
                x_rec,
                y_rec,
                marker="o",
                color=cores[idx],
                alpha=0.9,
                label=f"Iter {idx+1}"
            )

        ax.set_title(
            f"Critério {j+1}"
        )

        ax.set_xlabel(
            "Desempenho"
        )

        ax.set_ylabel(
            "Utilidade"
        )

        ax.set_ylim(0, 1)

        ax.grid(True)

        ax.legend(
            fontsize=8
        )

    plt.tight_layout()

    if save_path is not None:

        plt.savefig(
            save_path,
            dpi=300,
            bbox_inches="tight"
        )

    plt.close()


def plotar_real_vs_estimada(interpoladores, modelo_uta, save_prefix=None):

    num_criterios = len(interpoladores)

    for j in range(num_criterios):

        plt.figure(figsize=(5,4))

        x_min = interpoladores[j].x.min()
        x_max = interpoladores[j].x.max()

        x_real = np.linspace(x_min, x_max, 300)
        y_real = interpoladores[j](x_real)

        plt.plot(x_real, y_real, color="black", linewidth=3, label="Real")

        grupo = modelo_uta.grupos_w[j]
        w_j = modelo_uta.media_geral[grupo]

        y_rec = np.concatenate([[0], np.cumsum(w_j)])
        x_rec = modelo_uta.niveis[j]

        plt.plot(x_rec, y_rec, marker="o", linewidth=2, color="red", label="Estimated")

        plt.title(f"Critério {j+1}")
        plt.xlabel("Desempenho")
        plt.ylabel("Utilidade")
        plt.ylim(0,1)
        plt.grid(True)
        plt.legend()

        if save_prefix is not None:
            plt.savefig(f"{save_prefix}_criterio_{j+1}.png", dpi=300, bbox_inches="tight")

        plt.close()




def plotar_fronteiras_pareto(fronteiras, mins_globais=None, maxs_globais=None, save_path=None):

    plt.figure(figsize=(8,6))

    for i, fronteira in enumerate(fronteiras):

        objetivos = fronteira["objetivos"]

        plt.scatter(
            objetivos[:,0],
            objetivos[:,1],
            s=15,
            alpha=0.7,
            label=f"Frontier {i+1}"
        )

    if mins_globais is not None and maxs_globais is not None:

        plt.axvline(
            mins_globais[0],
            color="gray",
            alpha=0.5,
            linestyle="--",
            linewidth=1.5,
            label="Global Bounds"
        )

        plt.axvline(
            maxs_globais[0],
            color="gray",
            alpha=0.5,
            linestyle="--",
            linewidth=1.5,
            label="_nolegend_"
        )

        plt.axhline(
            mins_globais[1],
            color="gray",
            alpha=0.5,
            linestyle=":",
            linewidth=1.5,
            label="_nolegend_"
        )

        plt.axhline(
            maxs_globais[1],
            color="gray",
            alpha=0.5,
            linestyle=":",
            linewidth=1.5,
            label="_nolegend_"
        )

    plt.xlabel("Objective 1")
    plt.ylabel("Objective 2")
    plt.title("All Pareto Frontiers")

    plt.grid(True)
    plt.legend(loc="center left", bbox_to_anchor=(1.02, 0.5))
    plt.tight_layout()

    if save_path is not None:
        plt.savefig(save_path, dpi=300, bbox_inches="tight")

    debug_show()





def debug_utilidades(
    objetivos_brutos,
    utilidades_reais,
    utilidades_estimadas,
    ranking_real,
    ranking_estimado,
    top_n=10,
    alternativa_debug=0
):

    # =====================================================
    # DataFrame comparativo
    # =====================================================

    debug_df = pd.DataFrame({

        "u_real": np.round(
            utilidades_reais,
            4
        ),

        "u_est": np.round(
            utilidades_estimadas,
            4
        ),

        "rank_real": ranking_real,

        "rank_est": ranking_estimado

    })

    debug_df = debug_df.sort_values(
        "u_real",
        ascending=False
    )

    print("\n==============================")
    print("DATAFRAME DEBUG")
    print("==============================")

    print(
        debug_df.head(top_n)
    )

    # =====================================================
    # Top alternativas
    # =====================================================

    print("\n==============================")
    print("TOP REAL")
    print("==============================")

    print(
        np.argsort(
            -utilidades_reais
        )[:top_n]
    )

    print("\n==============================")
    print("TOP ESTIMADO")
    print("==============================")

    print(
        np.argsort(
            -utilidades_estimadas
        )[:top_n]
    )

    # =====================================================
    # Debug de uma alternativa específica
    # =====================================================

    print("\n==============================")
    print("DEBUG ALTERNATIVA")
    print("==============================")

    print(
        f"Alternativa: {alternativa_debug}"
    )

    print("\nObjetivos:")

    print(
        np.round(
            objetivos_brutos[
                alternativa_debug
            ],
            4
        )
    )

    print("\nUtilidade real:")

    print(
        np.round(
            utilidades_reais[
                alternativa_debug
            ],
            6
        )
    )

    print("\nUtilidade estimada:")

    print(
        np.round(
            utilidades_estimadas[
                alternativa_debug
            ],
            6
        )
    )

    print("\nRanking real:")

    print(
        ranking_real[
            alternativa_debug
        ]
    )

    print("\nRanking estimado:")

    print(
        ranking_estimado[
            alternativa_debug
        ]
    )


def adicionar_feedback_grupo(historico, alternativas, utilidades_reais, percentual):
    k = int(np.ceil(percentual * len(alternativas)))
    indices_preferidos = np.argsort(-utilidades_reais)[:k]
    grupo_preferido = [alternativas[i] for i in indices_preferidos]

    historico.append({
        "alternativas": alternativas,
        "grupo_preferido": grupo_preferido
    })

    return grupo_preferido






def adicionar_feedback_ranking(historico, alternativas, utilidades_reais):
    ordem = np.argsort(-utilidades_reais)
    ranking = [alternativas[i] for i in ordem]

    for melhor, pior in zip(ranking[:-1], ranking[1:]):
        historico.append({
            "alternativas": [melhor, pior],
            "grupo_preferido": [melhor]
        })

    return ranking





def plotar_comparacao_pos_otimizacao(interpoladores, modelo_uta, w_original, save_path=None):
    num_criterios = len(interpoladores)
    fig, axes = plt.subplots(1, num_criterios, figsize=(6 * num_criterios, 5))

    if num_criterios == 1:
        axes = [axes]

    for j, ax in enumerate(axes):
        x_min = interpoladores[j].x.min()
        x_max = interpoladores[j].x.max()
        x_real = np.linspace(x_min, x_max, 300)
        ax.plot(x_real, interpoladores[j](x_real), color="black", linewidth=3, label="Real")

        grupo = modelo_uta.grupos_w[j]
        x = modelo_uta.niveis[j]

        y_original = np.concatenate([[0], np.cumsum(w_original[grupo])])
        ax.plot(x, y_original, marker="o", linewidth=2, label="UTASTAR original")

        y_pos = np.concatenate([[0], np.cumsum(modelo_uta.media_geral[grupo])])
        ax.plot(x, y_pos, marker="o", linewidth=2, label="Após pós-otimização")

        ax.set_title(f"Critério {j + 1}")
        ax.set_xlabel("Desempenho")
        ax.set_ylabel("Utilidade")
        ax.set_ylim(0, 1)
        ax.grid(True)
        ax.legend()

    plt.tight_layout()

    if save_path is not None:
        plt.savefig(save_path, dpi=300, bbox_inches="tight")

    plt.close()


def testar_funcao_real_no_utastar(modelo_uta, interpoladores):
    w_real = []

    for j, niveis in enumerate(modelo_uta.niveis):
        valores = interpoladores[j](niveis)
        incrementos = np.diff(valores)
        w_real.extend(incrementos)

    w_real = np.array(w_real)

    print("\n===== TESTE FUNÇÃO REAL NO UTASTAR =====")
    print("Soma dos w reais projetados:", np.sum(w_real))

    violacoes = 0
    menor_folga = np.inf

    for k, m in enumerate(modelo_uta.m_w):
        diferenca = np.dot(m, w_real)

        if modelo_uta.tipos_comparacao[k] == ">":
            folga = diferenca - modelo_uta.delta
            menor_folga = min(menor_folga, folga)

            if diferenca < modelo_uta.delta:
                violacoes += 1

    print("Número de comparações:", len(modelo_uta.m_w))
    print("Número de violações:", violacoes)
    print("Menor folga:", menor_folga)

    return w_real


def plotar_real_vs_estimada_antes_aprendizado(interpoladores, pontos_estimados, save_path=None):
    num_criterios = len(interpoladores)
    fig, axes = plt.subplots(1, num_criterios, figsize=(6 * num_criterios, 5))

    if num_criterios == 1:
        axes = [axes]

    for j, ax in enumerate(axes):
        x_min = interpoladores[j].x.min()
        x_max = interpoladores[j].x.max()

        x_real = np.linspace(x_min, x_max, 300)
        y_real = interpoladores[j](x_real)

        ax.plot(x_real, y_real, color="black", linewidth=3, label="Real")

        x_est = pontos_estimados[j]["x"]
        y_est = pontos_estimados[j]["y"]

        ax.plot(x_est, y_est, marker="o", linewidth=2, label="Estimated before learning")

        #ax.set_title(f"Objective {j + 1}")
        ax.set_xlabel(f"Objective {j + 1} value", fontsize=14)
        ax.set_ylabel("Marginal value", fontsize=14)
        ax.set_ylim(0, 1)
        ax.grid(True)
        ax.legend(fontsize=12)

    plt.tight_layout()

    if save_path is not None:
        plt.savefig(save_path, dpi=300, bbox_inches="tight")

    plt.close()


def plotar_real_vs_estimada_depois_aprendizado(interpoladores, modelo_uta, save_path=None):
    num_criterios = len(interpoladores)
    fig, axes = plt.subplots(1, num_criterios, figsize=(6 * num_criterios, 5))

    if num_criterios == 1:
        axes = [axes]

    for j, ax in enumerate(axes):
        x_min = interpoladores[j].x.min()
        x_max = interpoladores[j].x.max()

        x_real = np.linspace(x_min, x_max, 300)
        y_real = interpoladores[j](x_real)

        ax.plot(x_real, y_real, color="black", linewidth=3, label="Real")

        grupo = modelo_uta.grupos_w[j]
        x_est = modelo_uta.niveis[j]

        y_est = np.concatenate([
            [0],
            np.cumsum(modelo_uta.media_geral[grupo])
        ])

        ax.plot(
            x_est,
            y_est,
            marker="o",
            linewidth=2,
            label="Estimated after learning"
        )

        #ax.set_title(f"Objective {j + 1}")
        ax.set_xlabel(f"Objective {j + 1} value", fontsize=14)
        ax.set_ylabel("Marginal value", fontsize=14)
        ax.set_ylim(0, 1)
        ax.grid(True)
        ax.legend(fontsize=12)

    plt.tight_layout()

    if save_path is not None:
        plt.savefig(
            save_path,
            dpi=300,
            bbox_inches="tight"
        )

    plt.close()


# ============================================================
# Weighted Kendall histórico
# ============================================================

def calcular_weighted_kendall_historico(
    fronteiras_anteriores,
    parametros_utilidade,
    tipo_utilidade,
    pesos_estimados,
    pontos_estimados
):
    kendalls_historicos = []

    for fronteira in fronteiras_anteriores:

        objetivos = fronteira["objetivos"]

        utilidades_reais = UtilityFunctions.avaliar_utilidade(
            objetivos,
            parametros_utilidade,
            tipo_utilidade
        )

        utilidades_estimadas = UtilityFunctions.avaliar_utilidade_estimada(
            objetivos,
            pesos_estimados,
            pontos_estimados
        )

        ranking_real = np.argsort(np.argsort(-utilidades_reais))
        ranking_estimado = np.argsort(np.argsort(-utilidades_estimadas))

        tau, _ = weightedtau(
            ranking_real,
            ranking_estimado
        )

        kendalls_historicos.append(tau)

    if len(kendalls_historicos) == 0:
        return [], np.nan

    return kendalls_historicos, np.mean(kendalls_historicos)


