# -*- coding: utf-8 -*-
"""Multiobjective knapsack problem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AHVMrBPTmyrwonkVylOBIVYtfK144ouO

# Problema da mochila multiobjetivo

\begin{align}
\max \quad &
\left(
z_1(x),
z_2(x),
\dots,
z_m(x)
\right)
\\[0.3cm]
\text{s.t.} \quad &
\sum_{i=1}^{n}
w_i x_i
\leq C
\\[0.3cm]
&
z_j(x)
=
\sum_{i=1}^{n}
p_{ij} x_i,
\quad
j = 1,\dots,m
\\[0.3cm]
&
x_i \in \{0,1\},
\quad
i = 1,\dots,n
\end{align}



*  $n$ is the number of items;
*  $m$ is the number of objectives;
* $w_i$ is the weight of item $i$;
* $C$ is the knapsack capacity;
*  $p_{ij}$ is the profit of item $i$ in objective $j$;
*  $x_i$ indicates whether item $i$ is selected.


Objectives could be:

profit;

quality;

sustainability;
"""

# =========================================================
# Bibliotecas
# =========================================================

import numpy as np

from scipy.optimize import milp
from scipy.optimize import Bounds
from scipy.optimize import LinearConstraint

# =========================================================
# Multiobjective Knapsack Problem (MOKP)
# =========================================================

class MOKP:

    # =====================================================
    # Inicialização
    # =====================================================

    def __init__(
        self,
        parametros
    ):

        self.parametros = parametros

        self.instancia = None

        self.fronteira = None


    # =====================================================
    # Geração da instância
    # =====================================================

    def gerar_instancia(self):

        np.random.seed(
            self.parametros["seed"]
        )

        # -------------------------------------------------
        # Quantidades
        # -------------------------------------------------

        n = self.parametros[
            "num_itens"
        ]

        m = self.parametros[
            "num_objetivos"
        ]

        # -------------------------------------------------
        # Pesos
        # -------------------------------------------------

        pesos = np.random.randint(

            self.parametros[
                "peso_min"
            ],

            self.parametros[
                "peso_max"
            ] + 1,

            size=n

        )

        # -------------------------------------------------
        # Lucros multiobjetivo
        # -------------------------------------------------

        lucros = np.random.randint(

            self.parametros[
                "lucro_min"
            ],

            self.parametros[
                "lucro_max"
            ] + 1,

            size=(n, m)

        )


        # -------------------------------------------------
        # Gerar capacidade a partir de um percentual aleatório da capacidade
        # -------------------------------------------------

        capacidade_percentual = np.random.uniform(

            self.parametros[
                "capacidade_min"
            ],

            self.parametros[
                "capacidade_max"
            ]

        )

        # -------------------------------------------------
        # Capacidade
        # -------------------------------------------------

        capacidade = int(

            capacidade_percentual

            *

            np.sum(pesos)

        )

        # -------------------------------------------------
        # Estrutura
        # -------------------------------------------------

        self.instancia = {

            "pesos": pesos,

            "lucros": lucros,

            "capacidade": capacidade,

            # Guardo a capacidade percentual para se quiser analisar depois se faz diferença percentuais maiores gerarem fronteira de pareto diferente
            "capacidade_percentual": capacidade_percentual,

            "num_itens": n,

            "num_objetivos": m

        }


    # =====================================================
    # Resolver weighted sum
    # =====================================================

    def resolver_weighted_sum(
        self,
        lambdas
    ):

        # -------------------------------------------------
        # Dados
        # -------------------------------------------------

        pesos = self.instancia[
            "pesos"
        ]

        lucros = self.instancia[
            "lucros"
        ]

        capacidade = self.instancia[
            "capacidade"
        ]

        n = self.instancia[
            "num_itens"
        ]

        # -------------------------------------------------
        # Objetivo agregado
        # -------------------------------------------------

        lucro_agregado = np.zeros(n)

        for j in range(

            self.instancia[
                "num_objetivos"
            ]

        ):

            lucro_agregado += (

                lambdas[j]

                *

                lucros[:,j]

            )

        # scipy minimiza
        c = -lucro_agregado

        # -------------------------------------------------
        # Restrição
        # -------------------------------------------------

        A = np.array([
            pesos
        ])

        lb = -np.inf

        ub = capacidade

        constraints = LinearConstraint(
            A,
            lb,
            ub
        )

        # -------------------------------------------------
        # Variáveis binárias
        # -------------------------------------------------

        integrality = np.ones(n)

        bounds = Bounds(

            lb=np.zeros(n),

            ub=np.ones(n)

        )

        # -------------------------------------------------
        # Resolve
        # -------------------------------------------------

        resultado = milp(

            c=c,

            constraints=constraints,

            integrality=integrality,

            bounds=bounds

        )

        return resultado


    # =====================================================
    # Geração da fronteira
    # =====================================================



    def gerar_fronteira(
        self,
        num_lambdas=100
    ):

        solucoes = []

        objetivos = []

        lambdas_usados = []

        # =================================================
        # Resolve para vários lambdas
        # =================================================

        for _ in range(num_lambdas):

            # -------------------------------------------------
            # Geração automática dos pesos
            # soma = 1
            # -------------------------------------------------

            lambdas = np.random.dirichlet(

                np.ones(

                    self.instancia[
                        "num_objetivos"
                    ]

                )

            )

            # -------------------------------------------------
            # Resolve
            # -------------------------------------------------

            resultado = self.resolver_weighted_sum(
                lambdas
            )

            if not resultado.success:

                continue

            # -------------------------------------------------
            # Solução binária. o código abaixo é porque o solver pode retornar float (mesmo sendo binário), é apenas para tirar o float e garantir que não tenha erro por tolerância numérica
            # -------------------------------------------------

            x = np.round(
                resultado.x
            ).astype(int)

            # -------------------------------------------------
            # Remove duplicadas. A soma ponderada retorna muitas soluções duplicadas, acredito que não faça sentido, então fazemos esta limpeza antes
            # -------------------------------------------------

            duplicada = False

            for s in solucoes:

                if np.array_equal(
                    s,
                    x
                ):

                    duplicada = True

                    break

            if duplicada:

                continue

            # -------------------------------------------------
            # Objetivos
            # -------------------------------------------------

            z = np.dot(

                x,

                self.instancia[
                    "lucros"
                ]

            )

            # -------------------------------------------------
            # Armazena
            # -------------------------------------------------

            solucoes.append(x)

            objetivos.append(z)

            lambdas_usados.append(
                lambdas
            )

        # =================================================
        # Estrutura final
        # =================================================

        self.fronteira = {

            "solucoes": np.array(
                solucoes
            ),

            "objetivos": np.array(
                objetivos
            ),

            "lambdas": np.array(
                lambdas_usados
            )

        }


    # =====================================================
    # Resumo
    # =====================================================

    def resumo(self):

        print("\n==============================")
        print("INSTÂNCIA MOKP")
        print("==============================")

        print(
            "Itens:",
            self.instancia["num_itens"]
        )

        print(
            "Objetivos:",
            self.instancia["num_objetivos"]
        )

        print(
            "Capacidade:",
            self.instancia["capacidade"]
        )

        if self.fronteira is not None:

            print(
                "Soluções fronteira:",
                len(
                    self.fronteira[
                        "solucoes"
                    ]
                )
            )