# -*- coding: utf-8 -*-
"""utastar_with_preferred_alt_groups_online_learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qj6Dqh_vJqwaauxAxulwW0jSZ1Qn5CCp

--------------------------------------------
# UTASTAR:
--------------------------------------------

### In this code, we use $U(a_{preferred})$ vs  $U(a_{others})$
"""

# =========================================================
# UTASTAR
# =========================================================

import numpy as np
from scipy.optimize import linprog
import matplotlib.pyplot as plt

MODO_POS="ambos"   # define se para a pós otimização, faz só "max", só "min" ou "ambos"


class UTASTAR:


    # =====================================================
    # Inicialização
    # =====================================================

    def __init__(

        self,

        alternativas,

        criterios,

        matriz_decisao,

        c_max,

        config_niveis,

        historico_preferencias,

        mins_globais=None,

        maxs_globais=None,

        delta=0.05,

        verbose=True, # Usar True se quiser imprimir os detalhes de cada função

        plot_utilidades=True # Usar True se quiser plotar as curvas de utilidade no final

    ):

        self.alternativas = alternativas

        self.criterios = criterios

        self.matriz = np.array(
            matriz_decisao
        )

        self.c_max = np.array(
            c_max
        )

        self.config_niveis = (
            config_niveis
        )

        self.historico_preferencias = (
            historico_preferencias
        )

        self.delta = delta

        self.verbose = verbose

        self.plot_utilidades = plot_utilidades

        self.mins_globais = mins_globais

        self.maxs_globais = maxs_globais


    # A função é para mandar o código imprimir o que tem dentro de self.log se self.verbose for True
    def log(

        self,

        *args

    ):

        if self.verbose:

            print(*args)


    # =====================================================
    # Geração automática dos níveis: pode ser all values (sendo que unique) ou interpolated (decidir em quantas partes - num_niveis)
    # =====================================================

    def gerar_niveis_criterios(
        self
    ):

        niveis = []

        self.log("\n===================================")
        self.log("GERAÇÃO DOS NÍVEIS")
        self.log("===================================")

        for j in range(
            self.matriz.shape[1]
        ):

            self.log("\n-----------------------------------")
            self.log(f"Critério {j+1}")
            self.log("-----------------------------------")

            valores = self.matriz[:,j]

            self.log("\nValores observados:")

            self.log(
                valores
            )

            config = self.config_niveis[j]

            self.log("\nConfiguração:")

            self.log(config)

            modo = config["modo"]

            self.log("\nModo:")

            self.log(modo)


            # -------------------------------------------------
            # all values
            # -------------------------------------------------

            if modo == "all_values":

                self.log("\nUsando TODOS os valores observados")

                niveis_j = np.unique(
                    valores
                )

                if self.c_max[j]:

                    niveis_j = np.sort(
                        niveis_j
                    )

                    self.log("\nValores únicos:")

                    self.log(niveis_j)

                else:

                    niveis_j = np.sort(
                        niveis_j
                    )[::-1]

            # -------------------------------------------------
            # interpolated
            # -------------------------------------------------

            elif modo == "interpolated":

                self.log("\nUsando níveis interpolados")

                num_niveis = config[
                    "num_niveis"
                ]

                self.log("\nNúmero de níveis:")

                self.log(num_niveis)

                if self.mins_globais is not None:
                    vmin = self.mins_globais[j]
                else:
                    vmin = np.min(valores)
                if self.maxs_globais is not None:
                    vmax = self.maxs_globais[j]
                else:
                    vmax = np.max(valores)


                niveis_j = np.linspace(

                    vmin,

                    vmax,

                    num_niveis

                )

                self.log("\nNíveis interpolados:")

                self.log(niveis_j)

                if self.c_max[j]:

                    niveis_j = np.sort(
                        niveis_j
                    )
                    self.log("\nCritério de MAXIMIZAÇÃO")

                else:

                    niveis_j = np.sort(
                        niveis_j
                    )[::-1]
                    self.log("\nCritério de MINIMIZAÇÃO")

            else:

                raise ValueError(
                    f"Modo inválido: {modo}"
                )

            self.log("\nNíveis finais:")
            self.log(niveis_j)


            niveis.append(
                niveis_j
            )

        self.niveis = niveis




    # =====================================================
    # Preparação automática dos dados
    # =====================================================

    def preparar_dados(
        self
    ):

        self.num_alternativas = (
            self.matriz.shape[0]
        )

        self.num_criterios = (
            self.matriz.shape[1]
        )

        # -------------------------------------------------
        # Índices alternativas
        # -------------------------------------------------

        mapa_alternativas = {}

        for i, nome in enumerate(
            self.alternativas
        ):

            mapa_alternativas[nome] = i

        self.mapa_alternativas = (
            mapa_alternativas
        )

        self.log("\nmapa_alternativas:")
        self.log(mapa_alternativas)




        # -------------------------------------------------
        # Comparações por grupo/iteração
        # -------------------------------------------------

        comparacoes = []

        for grupo_id, grupo in enumerate(self.historico_preferencias):

            self.log("\n===================================")

            self.log(f"Grupo de preferência {grupo_id+1}")

            self.log("===================================")

            alternativas_grupo = grupo[
                "alternativas"
            ]

            grupo_preferido = grupo[
                "grupo_preferido"
            ]


            # ---------------------------------------------
            # Grupo não preferido local
            # ---------------------------------------------

            grupo_nao_preferido = [alt for alt in alternativas_grupo if alt not in grupo_preferido]

            self.log("\nPreferidas:")
            self.log(grupo_preferido)

            self.log("\nNão preferidas:")
            self.log(grupo_nao_preferido)

            # ---------------------------------------------
            # Comparações locais
            # ---------------------------------------------

            for alt_pref in grupo_preferido:

                for alt_rest in grupo_nao_preferido:

                    comparacoes.append(

                        (
                            alt_pref,
                            alt_rest,
                            ">",
                            grupo_id
                        )

                    )

        self.comparacoes = comparacoes



        self.log("\n===================================")
        self.log("COMPARAÇÕES FINAIS")
        self.log("===================================")

        self.log(self.comparacoes)


        # -------------------------------------------------
        # Extrai o operador que existe na relação
        # para definir o tipo de restrição
        # (> preferência, = indiferença)
        # Não armazena as preferências entre alternativas
        # -------------------------------------------------
        self.tipos_comparacao = [

            c[2]

            for c in comparacoes

        ]

        self.log("\ntipos_comparacao:")
        self.log(self.tipos_comparacao)

        # -------------------------------------------------
        # níveis
        # -------------------------------------------------

        self.gerar_niveis_criterios()

        # -------------------------------------------------
        # Número de níveis de cada critério
        # (alpha_j no UTASTAR)
        # -------------------------------------------------

        alfa = []

        for n in self.niveis:

            alfa.append(
                len(n)
            )

        self.alfa = np.array(
            alfa
        )
        self.log("\nquantidade de níveis que cada critério tem (é o chamado alfa_j no artigo uta):")
        self.log(self.alfa)





    # =====================================================
    # Vetor utilidade
    # =====================================================

    def calcular_vetor_utilidade(

        self,

        valor, # valor observado da alternativa em certo critério

        niveis,

        criterio_max

    ):

        num_w = len(niveis) - 1

        vetor = np.zeros(num_w)


        # -------------------------------------------------
        # maximização
        # -------------------------------------------------

        if criterio_max:
            self.log("\nCritério de maximo:")

            if valor <= niveis[0]: # Valor abaixo da escala: nenhuma utilidade ativada

                self.log(f"O valor: {valor}, é menor ou igual que o nível mais baixo: {niveis[0]}")

                return vetor

            if valor >= niveis[-1]: # Valor acima da escala: utilidade máxima ativada, todos os valores serão 1

                vetor[:] = 1
                self.log(f"O valor: {valor}, é maior ou igual que o nível mais alto: {niveis[-1]}")

                return vetor

            for j in range(num_w):



                g0 = niveis[j]

                g1 = niveis[j+1]

                if g0 <= valor <= g1:

                    self.log(f"O valor: {valor}, denrto dos extremos: {niveis[0]},  {niveis[-1]}")

                    self.log(f"O valor: {valor}, está ENTRE níveis: {g0},  {g1}")

                    vetor[:j] = 1

                    alpha = (

                        (valor - g0)

                        /

                        (g1 - g0)

                    )

                    vetor[j] = alpha

                    self.log(f"{alpha:.4f}*u({g1}) + {(1-alpha):.4f}*u({g0})")

                    return vetor

        # -------------------------------------------------
        # minimização
        # -------------------------------------------------

        else:
            self.log("\nCritério de mínimo:")

            if valor <= niveis[-1]:

                vetor[:] = 1

                self.log(f"O valor: {valor}, é menor ou igual que o nível mais alto: {niveis[-1]}")

                return vetor

            if valor >= niveis[0]:

                self.log(f"O valor: {valor}, é menor ou igual que o nível mais baixo: {niveis[0]}")

                return vetor

            for j in range(num_w):

                g0 = niveis[j]

                g1 = niveis[j+1]




                if g1 <= valor <= g0:

                    self.log(f"O valor: {valor}, está denrto dos extremos: {niveis[0]},  {niveis[-1]}")

                    self.log(f"O valor: {valor}, está ENTRE níveis: {g1},  {g0}")

                    vetor[j+1:] = 1

                    alpha = (

                        (g0 - valor)

                        /

                        (g0 - g1)

                    )

                    vetor[j] = alpha

                    self.log( f"Interpolação linear: valor={valor}, intervalo=({g0},{g1}), alpha={alpha:.4f}")

                    return vetor

        return vetor


    # =====================================================
    # Vetores utilidade
    # =====================================================

    def gerar_vetores_utilidade(
        self
    ):

        vetores_utilidade = []

        for i in range(

            self.num_alternativas

        ):

            vetor_alt = []

            for j in range(

                self.num_criterios

            ):

                valor = self.matriz[i,j]

                vetor = (

                    self.calcular_vetor_utilidade(

                        valor,

                        self.niveis[j],

                        self.c_max[j]

                    )

                )

                vetor_alt.extend(
                    vetor
                )

            vetores_utilidade.append(
                vetor_alt
            )

        self.vetores_utilidade = np.array(
            vetores_utilidade
        )

        self.log(f"\nJunta os vetores do passo anterior para cada alternativa: {self.vetores_utilidade}")


    # =====================================================
    # Matriz m_w
    # =====================================================



    def gerar_matriz_mw(
        self
    ):

        m_w = []

        for (alt_a, alt_b, tipo, grupo_id) in self.comparacoes:

            idx_a = self.mapa_alternativas[
                alt_a
            ]

            idx_b = self.mapa_alternativas[
                alt_b
            ]

            self.log( f"\nGrupo {grupo_id+1} | Comparação: {alt_a} {tipo} {alt_b}")

            diferenca = self.vetores_utilidade[idx_a] - self.vetores_utilidade[idx_b]



            m_w.append(
                diferenca
            )

            self.log("\nDiferença:")
            self.log(diferenca)

        self.m_w = np.array(
            m_w
        )



        self.log(f"\nMatriz m_w: {self.m_w}")




    # =====================================================
    # Estrutura variáveis
    # =====================================================

    def criar_estrutura_variaveis(
        self
    ):

        num_w = np.sum(
            self.alfa - 1
        )

        self.num_w = int(
            num_w
        )

        self.num_comp = len(
            self.comparacoes
        )

        self.idx_w = np.arange(
            0,
            num_w
        )

        self.idx_sigma_mais = np.arange(

            num_w,

            num_w + self.num_comp

        )

        self.idx_sigma_menos = np.arange(

            num_w + self.num_comp,

            num_w + 2*self.num_comp

        )

        self.num_variaveis = (

            num_w

            +

            2*self.num_comp

        )


    # =====================================================
    # Função objetivo
    # =====================================================

    def criar_funcao_objetivo(
        self
    ):

        c = np.zeros(
            self.num_variaveis
        )

        c[
            self.idx_sigma_mais
        ] = 1

        c[
            self.idx_sigma_menos
        ] = 1

        self.c = c


    # =====================================================
    # Restrições
    # =====================================================

    def criar_restricoes(
        self
    ):

        A_ub = []

        b_ub = []

        A_eq = []

        b_eq = []

        for k in range(

            len(self.m_w)

        ):

            linha = np.zeros(
                self.num_variaveis
            )

            linha[
                self.idx_w
            ] = -self.m_w[k]

            linha[
                self.idx_sigma_mais[k]
            ] = 1

            linha[
                self.idx_sigma_menos[k]
            ] = -1



            # =================================================
            # O código abaixo é apenas para impressão legível da restrição
            # =================================================


            alt_a, alt_b, tipo, grupo_id = (self.comparacoes[k])

            termos = []

            # ---------------------------------------------
            # Parte dos w
            # ---------------------------------------------

            for idx in self.idx_w:

                coef = linha[idx]

                if abs(coef) > 1e-8:

                    termos.append(

                        f"{coef:.2f}*w{idx+1}"

                    )

            # ---------------------------------------------
            # Sigma+
            # ---------------------------------------------

            coef_sigma_mais = linha[
                self.idx_sigma_mais[k]
            ]

            if coef_sigma_mais != 0:

                termos.append(

                    f"+ {coef_sigma_mais:.0f}*sigma+{k+1}"

                )

            # ---------------------------------------------
            # Sigma-
            # ---------------------------------------------

            coef_sigma_menos = linha[
                self.idx_sigma_menos[k]
            ]

            if coef_sigma_menos != 0:

                termos.append(

                    f"{coef_sigma_menos:.0f}*sigma-{k+1}"

                )

            # ---------------------------------------------
            # Junta expressão
            # ---------------------------------------------

            expressao = " ".join(
                termos
            )

            # ---------------------------------------------
            # Imprime
            # ---------------------------------------------

            self.log("\n===================================")

            self.log(
                f"Restrição {k+1}"
            )

            self.log(
                f"Grupo {grupo_id+1}: {alt_a} {tipo} {alt_b}"
            )

            if tipo == ">":

                self.log(

                    f"{expressao} <= {-self.delta}"

                )

            elif tipo == "=":

                self.log(

                    f"{expressao} = 0"

                )


            # =================================================
            # O código acima é apenas para impressão legível da restrição
            # =================================================



            if self.tipos_comparacao[k] == ">":

                A_ub.append(
                    linha
                )

                b_ub.append(
                    -self.delta
                )

            elif (

                self.tipos_comparacao[k]

                == "="

            ):

                A_eq.append(
                    -linha
                )

                b_eq.append(0)

        linha_norm = np.zeros(
            self.num_variaveis
        )

        linha_norm[
            self.idx_w
        ] = 1

        A_eq.append(
            linha_norm
        )

        b_eq.append(1)

        self.A_ub = np.array(
            A_ub
        )

        self.b_ub = np.array(
            b_ub
        )

        self.A_eq = np.array(
            A_eq
        )

        self.b_eq = np.array(
            b_eq
        )


    # =====================================================
    # Bounds - os limites permitidos para cada variável do LP
    # =====================================================

    def criar_bounds(
        self
    ):

        bounds = []

        for _ in range(
            self.num_variaveis
        ):

            bounds.append(
                (0, None)
            )

        self.bounds = bounds






    # =====================================================
    # Resolver UTASTAR
    # =====================================================

    def resolver_utastar(
        self
    ):

        resultado = linprog(

            c=self.c,

            A_ub=self.A_ub,

            b_ub=self.b_ub,

            A_eq=self.A_eq,

            b_eq=self.b_eq,

            bounds=self.bounds,

            method="highs"

        )

        self.resultado = resultado

        self.log("\n====================")
        self.log("RESULTADO LP")
        self.log("====================")
        self.log(f"Success: {resultado.success}")
        self.log(f"FO ótima: {resultado.fun:.10f}")
        self.log("\n====================")
        self.log("FO OTIMA")
        self.log("====================")
        self.log(resultado.fun)



    # =====================================================
    # Pipeline principal
    # =====================================================

    def run(
        self
    ):

        self.preparar_dados()

        self.gerar_vetores_utilidade()

        self.gerar_matriz_mw()

        self.criar_estrutura_variaveis()

        self.criar_funcao_objetivo()

        self.criar_restricoes()

        self.criar_bounds()

        self.resolver_utastar()










    # =====================================================
    # Plot das utilidades marginais recuperadas
    # =====================================================

    def plotar_funcoes_utilidade_recuperadas(
        self
    ):


        # =================================================
        # Critérios
        # =================================================

        for j, grupo in enumerate(

            self.grupos_w

        ):

            # ---------------------------------------------
            # Incrementos do critério
            # ---------------------------------------------

            w_j = self.media_geral[grupo]

            # ---------------------------------------------
            # Utilidade acumulada
            # ---------------------------------------------

            utilidade = np.concatenate([

                [0],

                np.cumsum(w_j)

            ])

            # ---------------------------------------------
            # Níveis do critério
            # ---------------------------------------------

            niveis = self.niveis[j]

            # ---------------------------------------------
            # Plot
            # ---------------------------------------------

            plt.figure(figsize=(5,4))

            plt.plot(

                niveis,

                utilidade,

                marker="o"

            )

            plt.title(
                f"Critério {j+1}"
            )

            plt.xlabel(
                "Nível"
            )

            plt.ylabel(
                "Utilidade"
            )

            plt.grid(True)

            #if not self.c_max[j]:
              #plt.gca().invert_xaxis()

            plt.show()



    # =====================================================
    # Índices w por critério
    # =====================================================

    def gerar_grupos_w(
        self
    ):

        grupos = []

        inicio = 0

        for alfa_j in self.alfa:

            fim = inicio + (
                alfa_j - 1
            )

            grupos.append(

                np.arange(
                    inicio,
                    fim
                )

            )

            inicio = fim

        self.grupos_w = grupos






    # =====================================================
    # Pós otimização
    # =====================================================

    def pos_otimizacao(

        self,

        criterio_idx,

        tipo,

        epsilon=1e-2

    ):

        z_otimo = self.resultado.fun

        linha_z = np.zeros(
            self.num_variaveis
        )

        linha_z[
            self.idx_sigma_mais
        ] = 1

        linha_z[
            self.idx_sigma_menos
        ] = 1

        A_ub_pos = np.vstack([

            self.A_ub,

            linha_z

        ])

        b_ub_pos = np.append(

            self.b_ub,

            z_otimo + epsilon

        )

        c_pos = np.zeros(
            self.num_variaveis
        )

        if tipo == "max":

            c_pos[
                self.grupos_w[
                    criterio_idx
                ]
            ] = -1

        elif tipo == "min":

            c_pos[
                self.grupos_w[
                    criterio_idx
                ]
            ] = 1

        self.log("\n====================")
        self.log(f"Critério {criterio_idx + 1} | {tipo}")
        self.log("OBJETIVO POS")
        self.log(c_pos[self.idx_w])

        resultado_pos = linprog(

            c=c_pos,

            A_ub=A_ub_pos,

            b_ub=b_ub_pos,

            A_eq=self.A_eq,

            b_eq=self.b_eq,

            bounds=self.bounds,

            method="highs"

        )

        self.log("SOLUCAO")
        self.log(np.round(resultado_pos.x[self.idx_w], 6))

        self.log("FO POS")
        self.log(resultado_pos.fun)

        return resultado_pos


    # =====================================================
    # Executa pós otimização
    # =====================================================

    def run_pos_otimizacao(self, epsilon=1e-2):

        self.gerar_grupos_w()

        solucoes_max = []
        solucoes_min = []

        tipos = ["max"] if MODO_POS == "max" else ["min"] if MODO_POS == "min" else ["max", "min"]

        for j in range(self.num_criterios):

            for tipo in tipos:

                resultado_pos = self.pos_otimizacao(criterio_idx=j, tipo=tipo, epsilon=epsilon)

                if not resultado_pos.success:
                    self.log("\n====================")
                    self.log(f"Critério {j + 1} | {tipo}")
                    self.log("Pós-otimização falhou")

                    continue

                self.log("\n====================")
                self.log(f"Critério {j + 1} | {tipo}")

                grupo = self.grupos_w[j]

                self.log("Incrementos:")
                self.log(np.round(resultado_pos.x[grupo], 6))

                self.log("FO POS")
                self.log(resultado_pos.fun)

                self.log("Soma:")
                self.log(np.sum(resultado_pos.x[grupo]))

                w_pos = resultado_pos.x[self.idx_w]

                if tipo == "max":
                    solucoes_max.append(w_pos)
                else:
                    solucoes_min.append(w_pos)

        self.solucoes_max = np.array(solucoes_max)
        self.solucoes_min = np.array(solucoes_min)

        self.log("Número soluções max:")
        self.log(len(self.solucoes_max))
        self.log("Número soluções min:")
        self.log(len(self.solucoes_min))

        if len(self.solucoes_max) > 0:
            self.media_max = np.mean(self.solucoes_max, axis=0)

        if len(self.solucoes_min) > 0:
            self.media_min = np.mean(self.solucoes_min, axis=0)

        w_min_real = np.min(
            np.vstack([self.solucoes_max, self.solucoes_min]),
            axis=0
        )

        w_max_real = np.max(
            np.vstack([self.solucoes_max, self.solucoes_min]),
            axis=0
        )

        self.log("\n====================")
        self.log("RANGE REAL DOS W")
        self.log("====================")

        for k in range(len(w_min_real)):
            self.log(
                f"w{k + 1}: min={w_min_real[k]:.6f} max={w_max_real[k]:.6f}"
            )

        if MODO_POS == "max":
            self.media_geral = self.media_max
        elif MODO_POS == "min":
            self.media_geral = self.media_min
        else:
            self.media_geral = np.mean(np.vstack([self.solucoes_max, self.solucoes_min]), axis=0)

        if self.plot_utilidades:
            self.plotar_funcoes_utilidade_recuperadas()

        self.log("\n====================")
        self.log("INCREMENTOS FINAIS")

        for j, grupo in enumerate(self.grupos_w):
            self.log(f"Critério {j + 1}")
            self.log(np.round(self.media_geral[grupo], 4))
            self.log(f"Soma = {np.sum(self.media_geral[grupo]):.4f}")









    # =====================================================
    # Pesos MAVT
    # =====================================================

    def calcular_pesos_criterios(
        self,
        w=None
    ):

        if w is None:

            w = self.media_geral

        pesos_criterios = []

        inicio = 0

        for alfa_j in self.alfa:

            fim = inicio + (
                alfa_j - 1
            )

            peso_j = np.sum(
                w[inicio:fim]
            )

            pesos_criterios.append(
                peso_j
            )

            inicio = fim

        self.pesos_criterios = np.array(
            pesos_criterios
        )