# -*- coding: utf-8 -*-
"""utility_functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aQDLpnB9x9PawvJoGPIHILjxtIu-xB-5
"""

# =========================================================
# Utility Functions
# =========================================================

import numpy as np
from scipy.interpolate import PchipInterpolator
import matplotlib.pyplot as plt



class UtilityFunctions:


    # =====================================================
    # Geração dos pesos reais
    # =====================================================

    @staticmethod
    def gerar_pesos_reais(
        num_criterios,
        seed
    ):

        rng = np.random.default_rng(
            seed
        )

        pesos_reais = rng.dirichlet(
            np.ones(
                num_criterios
            )
        )

        return pesos_reais







    # =====================================================
    # Geração dos pontos para gerar a função de utilidade dependo do tipo de função.
    # Os valores não estão normalizados
    # Precisa considerar se é critério de max ou min
    # =====================================================

    @staticmethod
    def gerar_pontos_utilidade(
          pesos,
          tipo_utilidade,
          mins_globais,
          maxs_globais,
          c_max,
          seed=None
      ):

        #Garantir que será gerado sempre igual se o seed for igual
        rng = np.random.default_rng(seed)

        pontos_utilidade = []

        # =================================================
        # Critérios
        # =================================================

        for j, w_j in enumerate(pesos):

            x_min = mins_globais[j]

            x_max = maxs_globais[j]

            # ---------------------------------------------
            # Linear - como os valores dos critérios não estão normalizados, precisa considerar se é de max ou min
            # ---------------------------------------------

            if tipo_utilidade == "linear":

                if c_max[j]:
                  pontos_j = np.array([
                      [x_min, 0.0],
                      [x_max, w_j]
                  ])

                else:
                  pontos_j = np.array([
                      [x_min, w_j],
                      [x_max, 0.0]
                  ])


            # ---------------------------------------------
            # Não - Linear
            # ---------------------------------------------

            elif tipo_utilidade == "convexa":

                # -----------------------------------------
                # Primeiro ponto interno
                # crescimento lento inicial
                # -----------------------------------------

                y1 = rng.uniform(
                    0.05 * w_j,
                    0.30 * w_j
                )

                # -----------------------------------------
                # Segundo ponto interno
                # crescimento mais acelerado
                # -----------------------------------------

                y2 = rng.uniform(
                    y1 + 0.10 * w_j,
                    0.80 * w_j
                )

                # -----------------------------------------
                # Estrutura final
                # -----------------------------------------

                if c_max[j]:
                  pontos_j = np.array([
                      [x_min, 0.0],
                      [x_min + 0.3*(x_max-x_min), y1],
                      [x_min + 0.7*(x_max-x_min),y2],
                      [x_max, w_j]
                  ])

                else:
                    pontos_j = np.array([
                        [x_min, w_j],
                        [
                            x_min + 0.3*(x_max-x_min),
                            w_j - y1
                        ],
                        [
                            x_min + 0.7*(x_max-x_min),
                            w_j - y2
                        ],
                        [x_max, 0.0]
                    ])



            # ---------------------------------------------
            # Tipo inválido
            # ---------------------------------------------

            else:
                raise ValueError(
                    f"Tipo inválido: {tipo_utilidade}"
                )

            pontos_utilidade.append(
                pontos_j
            )

        return pontos_utilidade












    # =====================================================
    # Geração dos interpoladores - depois de gerar os pontos da curva, vamos interpolar
    # =====================================================

    @staticmethod
    def gerar_interpoladores(
        pontos_utilidade
    ):

        interpoladores = []

        # =================================================
        # Critérios
        # =================================================

        for pontos_j in pontos_utilidade:

            # -------------------------------------------------
            # Coordenadas: x_pontos pega os valores de x (coluna 0) e y pontos pega os valores de y (coluna 1)
            # -------------------------------------------------

            x_pontos = pontos_j[:,0]

            y_pontos = pontos_j[:,1]

            # -------------------------------------------------
            # Interpolador suave: a função do Python constrói internamente: vários polinômios cúbicos; um para cada intervalo.
            # Teoricamente a curva fica contínua, derivável e suave
            # documentação: https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.PchipInterpolator.html
            # Quando é linear neste meu caso, ele só tem dois pontos então tem que fazer uma reta
            # Garante monotonicidade
            # -------------------------------------------------

            interpolador = PchipInterpolator(

                x_pontos,

                y_pontos

            )

            interpoladores.append(
                interpolador
            )

        return interpoladores






    # =====================================================
    # Função que pega os pontos da curva de pareto e associa à respectiva utilidade a partir da função de utilidade real que temos
    # =====================================================

    @staticmethod
    def avaliar_utilidade(

        objetivos,

        parametros_utilidade,

        tipo_utilidade

    ):

        # -------------------------------------------------
        # Objetivos
        # -------------------------------------------------

        objetivos = np.array(

            objetivos,

            dtype=float

        )


        interpoladores = (
            parametros_utilidade[
                "interpoladores"
            ]
        )

        # -------------------------------------------------
        # Quantidades
        # -------------------------------------------------

        num_alternativas = (
            objetivos.shape[0]
        )

        num_criterios = (
            objetivos.shape[1]
        )

        # -------------------------------------------------
        # Vetor final
        # -------------------------------------------------

        utilidades = np.zeros(
            num_alternativas
        )

        # =================================================
        # Alternativas
        # =================================================

        for i in range(num_alternativas):

            utilidade_i = 0

            # =============================================
            # Critérios
            # =============================================

            for j in range(
                num_criterios
            ):

                # -----------------------------------------
                # Valor bruto do critério
                # -----------------------------------------

                x = objetivos[i,j]


                u = interpoladores[j](x)

                utilidade_i += u

            utilidades[i] = utilidade_i

        return utilidades













    # =====================================================
    # Plot das funções de utilidade
    # =====================================================

    @staticmethod
    def plotar_funcoes_utilidade(interpoladores, pontos_utilidade, save_prefix=None):
        from matplotlib.ticker import MaxNLocator

        for j, interpolador in enumerate(interpoladores):
            x_min = pontos_utilidade[j][:, 0].min()
            x_max = pontos_utilidade[j][:, 0].max()
            margem_x = 0.03 * (x_max - x_min)

            x_grid = np.linspace(x_min, x_max, 200)
            y_grid = interpolador(x_grid)

            plt.figure(figsize=(5, 4))
            plt.plot(x_grid, y_grid, color="black", linewidth=3)

            plt.xlabel(f"Objective {j + 1} value", fontsize=14)
            plt.ylabel("Marginal value", fontsize=14)
            plt.xticks(fontsize=12)
            plt.yticks(fontsize=12)

            plt.xlim(x_min - margem_x, x_max + margem_x)
            plt.gca().xaxis.set_major_locator(MaxNLocator(nbins=5))

            plt.ylim(0, 1)
            plt.grid(True, alpha=0.35)

            if save_prefix is not None:
                plt.savefig(
                    f"{save_prefix}_criterio_{j + 1}.png",
                    dpi=300,
                    bbox_inches="tight"
                )

            plt.close()



    # =====================================================
    # função para avaliar utilidade estimada
    # =====================================================


    @staticmethod
    def avaliar_utilidade_estimada(
        matriz,
        pesos,
        pontos_utilidade
    ):

        num_alternativas = matriz.shape[0]

        num_criterios = matriz.shape[1]

        utilidades = np.zeros(
            num_alternativas
        )

        for i in range(num_alternativas):

            soma = 0

            for j in range(num_criterios):

                x = matriz[i,j]

                x_pontos = pontos_utilidade[j]["x"]

                y_pontos = pontos_utilidade[j]["y"]

                u = np.interp(
                    x,
                    x_pontos,
                    y_pontos
                )

                #soma += pesos[j] * u
                soma += u

            utilidades[i] = soma

        return utilidades